Traveling on Taman Impian Jaya Ancol
====================================
Sukma Wardana <swardana@tutanota.com>
v1.0, 2022-03-28
:jbake-type: post
:jbake-tags: travel, ancol
:jbake-status: published
:jbake-spoiler: Visiting the largest integrated tourism area in South East Asia

Disclaimer:
The activity is occured on March 25th 2022 till March 26th 2022.
The price, available attraction, and mechanism on buying the ticket could be different by today.

After two years living in the capital city of Indonesia.
Finally, I visited Taman Impian Jaya Ancol.
I would called it Ancol for the sake of brievity.

Actually, I don't have any plan to visit Ancol.
Me and my Wife still adapting with our new life.
Becoming a parent is really hard.

One day, my mother call me.
She said that want to visit us in Jakarta.
The agenda is to seeing my litle baby and have a vacation before Ramadan.
Which mean, my parents and my two younger sister and brother will come in Jakarta.

My litle house couldn't take all of them.
So, I need to find a hotel for my family.
And think about destination that could be use for our short vacation.

I saw this is a good opportunity.
Me and my Wife never take any vacation after having a baby.
We need fresh air.

So, the quest begin.

Actually, if we excluding Mall, Cafe, and Museum.
Jakarta have very limited spot for family vacation.
After many search, I found nice place from https://www.instagram.com/adindafala/[Adinda Fala] Instagram Stories.

Her stories is about breakfast time near swiming pool with sea view.
It's about her vacation in https://www.putriduyungresort.com[Putri Duyung Resort].
And I was like it.
It really give the vibe of family vacation.
Because, she also bring her kid.

